# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170514_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
