# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_user_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
