# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='image_for_thumbnail',
            field=models.CharField(default=b'Well..', max_length=500),
        ),
    ]
