# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_info_image_for_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_for_month',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('app.user_info',),
        ),
        migrations.CreateModel(
            name='report_for_today',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('app.user_info',),
        ),
        migrations.CreateModel(
            name='report_for_year',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('app.user_info',),
        ),
    ]
